


[General]
# MAVLink TCP server port for GCS
TcpServerPort=5760
ReportStats=false
# Set MAVLink dialect (common or ardupilotmega)
#MavlinkDialect=common

# UART endpoint for flight controller via /dev/ttyAMA0
[UartEndpoint serial-AMA4]
Device=/dev/ttyAMA0
#Device=/dev/ttyAMA4
Baud=921600

# UDP endpoint for local system 2
#[UdpEndpoint local2]
#Mode=normal
#Address=192.168.1.100
#Port=14550

# UDP endpoint for local system adapter 2
#[UdpEndpoint local2]
#Mode=normal
#Address=192.168.1.215
#Port=14550

# UDP endpoint for WFB-NG communication
[UdpEndpoint WFB-NG]
Mode=normal
Address=127.0.0.1
Port=14550

# UDP endpoint for the drone's ZeroTier network (Local IP)
#[UdpEndpoint DroneZeroTier]
#Mode=normal
#Address=192.168.192.247
#Port=14555

# UDP endpoint for ZeroTier virtual network (GCS IP)
#[UdpEndpoint ZeroTierGCS]
#Mode=normal
#Address=192.168.192.63
#Port=14555


